/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vu_guest;





import java.awt.Frame;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Set;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import projectinterface.CentralInterface;

/**
 *
 * @author KeVin
 */
public class Customer extends javax.swing.JPanel implements CentralInterface{

    private Frame JFrame;
    DefaultTableModel cusmodel,resmodel;
    Vector<CustomerEnity> cusEnity;
    Vector<CustomerEnity> rescus;
    CustomerEnity cusObj;
    CustomerDao cusdao;
    Vector header,data,row,rheader,rdata,rrow;
    String identifier,fullname,gen,company,address,phone,email,status;
    Date age;
    int cusid;
    HashMap<String, Vector> result;
    
    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();     
        
        header=new Vector();
        data=new Vector();
        header.add("Customer ID");
        header.add("Person Identifier");
        header.add("Age");
        header.add("Full Name");
        header.add("Gender");
        header.add("Company");
        header.add("Address");
        header.add("Phone");
        header.add("Email");
        header.add("Status");   
                
        cusmodel=new DefaultTableModel(data,header){
            @Override
            public boolean isCellEditable(int rows,int column){
                return false;
            }
            
        };
        custable.setModel(cusmodel);
        showData();
        bedit.setEnabled(false);
        
        rheader=new Vector();
        rdata=new Vector();
        rheader.add("Reservation ID");
        rheader.add("Customer ID");
        rheader.add("Full Name");
               
        resmodel=new DefaultTableModel(rdata,rheader){
            @Override
            public boolean isCellEditable(int rows,int column){
                return false;
            }
            
        };
        restable.setModel(resmodel);
        showres();
    }
    public void showres(){
            resmodel.setRowCount(0);
            cusdao=new CustomerDao();
            cusEnity=cusdao.rescus();
            for (CustomerEnity cus : cusEnity) {
                rrow=new Vector();
                rrow.addElement(cus.getResid());
                rrow.addElement(cus.getCusID());
                rrow.addElement(cus.getFullname());
                rdata.add(rrow);
            }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        tphone = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tidentifier = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        custable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        badd = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        restable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        jLabel7.setText("Phone");

        jLabel6.setText("Name");

        tname.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tnameCaretUpdate(evt);
            }
        });

        tphone.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tphoneCaretUpdate(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0);
        flowLayout2.setAlignOnBaseline(true);
        jPanel3.setLayout(flowLayout2);

        jLabel2.setBackground(new java.awt.Color(0, 0, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Customers");
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(jLabel2);

        jLabel1.setText("Identifier");

        tidentifier.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tidentifierCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tphone)
                            .addComponent(tname)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tidentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tidentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(456, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setForeground(new java.awt.Color(102, 0, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(102, 51, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(51, 0, 255));

        custable.setForeground(new java.awt.Color(51, 51, 51));
        custable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        custable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        custable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                custableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(custable);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        badd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon24/add24.png"))); // NOI18N
        badd.setText("Add");
        badd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });
        jPanel2.add(badd);

        bedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon24/edit.png"))); // NOI18N
        bedit.setText("Edit");
        bedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beditMouseClicked(evt);
            }
        });
        jPanel2.add(bedit);

        restable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        restable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(restable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Detail", jPanel6);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        jTabbedPane2.addTab("Customers", jPanel5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        Addcustomer add=new Addcustomer(JFrame, true);
        add.setVisible(true);
        showData();
        showres();
        
    }//GEN-LAST:event_baddActionPerformed

    private void tnameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tnameCaretUpdate
        cusmodel.getDataVector().clear();
        showData();
        Vector obj =  cusmodel.getDataVector();
        result = new HashMap<>();
        int i =1;
        for (Object customer : obj) {
            Vector cus = (Vector) customer;
            result.put(cus.get(3).toString()+i, cus);
            i++;
        }
        Set object = result.keySet();
        String word = tname.getText();
        Iterator words = object.iterator();
        Vector sub = new Vector();
        while (words.hasNext()) {
            Object next = words.next();
            if(next.toString().toLowerCase().contains(word)){
                sub.add(next);
            }
            //d.addWord(next.toString());
        }
        //System.err.println(result.get("Lai Van Trach").toString());
        cusmodel.getDataVector().clear();
        if(!sub.isEmpty()){
            for (Object ob : sub) {
                cusmodel.addRow(result.get(ob.toString()));
            }
        }
        custable.setModel(cusmodel);
        repaint();
    }//GEN-LAST:event_tnameCaretUpdate

    private void tphoneCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tphoneCaretUpdate
        cusmodel.getDataVector().clear();
        showData();
        Vector obj =  cusmodel.getDataVector();
        result = new HashMap<>();
        int i =1;
        for (Object customer : obj) {
            //System.out.println(customer.toString());
            Vector cus = (Vector) customer;
            result.put(cus.get(7).toString()+i, cus);
            i++;
        }
        Set object = result.keySet();
        
            //System.out.println(object.toString());
        // basic testing code to get started
        String word = tphone.getText();
        // Pass NearbyWords any Dictionary implementation you prefer

        Iterator words = object.iterator();
        Vector sub = new Vector();
        while (words.hasNext()) {
            Object next = words.next();
            if(next.toString().toLowerCase().contains(word)){
                sub.add(next);
            }
            //d.addWord(next.toString());
        }
        //System.err.println(result.get("Lai Van Trach").toString());
        cusmodel.getDataVector().clear();
        if(!sub.isEmpty()){
            for (Object ob : sub) {
                cusmodel.addRow(result.get(ob.toString()));
            }
        }
        custable.setModel(cusmodel);
        repaint();
        //System.out.println("Spelling Suggestions for \""+word+"\" are:");
        //System.out.println(suggest);
    }//GEN-LAST:event_tphoneCaretUpdate

    private void tidentifierCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tidentifierCaretUpdate
        cusmodel.getDataVector().clear();
        showData();
        Vector obj =  cusmodel.getDataVector();
        result = new HashMap<>();
        int i = 1;
        for (Object customer : obj) {
            //System.out.println(customer.toString());
            Vector cus = (Vector) customer;
            result.put(cus.get(1).toString()+i, cus);
            i++;
        }
        Set object = result.keySet();
        
            //System.out.println(object.toString());
        // basic testing code to get started
        String word = tidentifier.getText();
        // Pass NearbyWords any Dictionary implementation you prefer

        Iterator words = object.iterator();
        Vector sub = new Vector();
        while (words.hasNext()) {
            Object next = words.next();
            if(next.toString().contains(word)){
                sub.add(next);
            }
        }
        cusmodel.getDataVector().clear();
        if(!sub.isEmpty()){
            for (Object ob : sub) {
                cusmodel.addRow(result.get(ob.toString()));
            }
        }
        custable.setModel(cusmodel);
        repaint();
    }//GEN-LAST:event_tidentifierCaretUpdate

    private void custableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custableMouseClicked
                int i=custable.getSelectedRow();
                int b=custable.getSelectedColumn();
                cusid = (int) custable.getValueAt(i, 0);
                identifier = (String) custable.getValueAt(i, 1);
                age=(Date) custable.getValueAt(i, 2);
                fullname = (String) custable.getValueAt(i, 3);
                gen=(String) custable.getValueAt(i, 4);
                company=(String) custable.getValueAt(i, 5);
                address=(String) custable.getValueAt(i, 6);
                phone=(String) custable.getValueAt(i, 7);
                email = (String) custable.getValueAt(i, 8);
                status= (String) custable.getValueAt(i, 9);
                bedit.setEnabled(true);
                if(i==-1){
                    JOptionPane.showMessageDialog(this, "No select row0");
                    return;
                }
                if(evt.getClickCount()==2){
                
                CustomerEnity cusObj=new CustomerEnity(identifier, fullname, gen, company, address, phone, email, status, (java.sql.Date) age, cusid);
                Addcustomer add=new Addcustomer(JFrame, true);
                if(cusObj==null){
                    return;
                }
                add.showupdate(cusObj,false);
                add.setVisible(true);
                showData();
                showres();
                }
                
                
             
    }//GEN-LAST:event_custableMouseClicked

    private void beditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beditMouseClicked
                int i=custable.getSelectedRow();
                int b=custable.getSelectedColumn();
                cusid = (int) custable.getValueAt(i, 0);
                identifier = (String) custable.getValueAt(i, 1);
                age=(Date) custable.getValueAt(i, 2);
                fullname = (String) custable.getValueAt(i, 3);
                gen=(String) custable.getValueAt(i, 4);
                company=(String) custable.getValueAt(i, 5);
                address=(String) custable.getValueAt(i, 6);
                phone=(String) custable.getValueAt(i, 7);
                email = (String) custable.getValueAt(i, 8);
                status= (String) custable.getValueAt(i, 9);
                bedit.setEnabled(true);
                if(i==-1){
                    JOptionPane.showMessageDialog(this, "No select row0");
                    return;
                }
                if(evt.getClickCount()==1){
                
                CustomerEnity cusObj=new CustomerEnity(identifier, fullname, gen, company, address, phone, email, status, (java.sql.Date) age, cusid);
                Addcustomer add=new Addcustomer(JFrame, true);
                if(cusObj==null){
                    return;
                }
                add.showupdate(cusObj,false);
                add.setVisible(true);
                showData();
                showres();
                }
                
    }//GEN-LAST:event_beditMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton badd;
    private javax.swing.JButton bedit;
    private javax.swing.JTable custable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable restable;
    private javax.swing.JTextField tidentifier;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tphone;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void formDisplayCentral() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

    @Override
    public void showData() {
        
            //data = new Vector();
            cusmodel.setRowCount(0);
            cusdao = new CustomerDao();
            cusEnity=cusdao.getCollection();
            for (CustomerEnity cus : cusEnity) {
            row=new Vector();
            row.addElement(cus.getCusID());
            row.addElement(cus.getIdentifier());
            row.addElement(cus.getAge());
            row.addElement(cus.getFullname());
            row.addElement(cus.getGender());
            row.addElement(cus.getCompany());
            row.addElement(cus.getAddress());
            row.addElement(cus.getPhone());
            row.addElement(cus.getEmail());
            row.addElement(cus.getStatus());
            data.add(row);
            
            custable.setAutoCreateRowSorter(true);
        }
            
            
    }       

    @Override
    public boolean checkEmptyField() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
        
    
}
