/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hung_RoomType;


import hung_Room.RoomDAO;
import hung_Room.RoomEntity;
import java.awt.Frame;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projectinterface.CentralInterface;

/**
 *
 * @author Hung nguyen
 */
public class RoomType extends javax.swing.JPanel implements CentralInterface{

    private Frame JFrame;
    DefaultTableModel roomTypeListModel;
    DefaultTableModel roomTypeDetailsModel;
    Vector header,data,row;
    Vector headerDetails,dataDetails,rowDetails;
    
    RoomTypeDAO roomTypeDOA;
    RoomDAO roomDOA;
    
    RoomTypeEntity roomTypeEntity;
    RoomEntity roomEntity;
    
    Vector<RoomTypeEntity> roomTypeEntityCollection;
    Vector<RoomEntity> roomEntityCollection;
    /**
     * Creates new form Customer
     */
    public RoomType() {
        initComponents();
        
        data = new Vector();
        roomTypeListModel = new DefaultTableModel();
        roomTypeDetailsModel = new DefaultTableModel();
        
        setHeaderDetail();
        showData();
    }
    private void setHeaderList() {
        header = new Vector();
        header.add("Type ID");
        header.add(" Name");
        header.add(" Rate");
        header.add("Note");
        roomTypeListModel.setDataVector(data, header);
        tblRoomTypeList.setModel(roomTypeListModel);
    }
    
    private void setDetailsModel(int roomTypeIDdetail, double roomTypeRateDetails, String roomTypeNameDetails) {

        roomDOA = new RoomDAO();
        roomTypeDOA = new RoomTypeDAO();
        
        roomEntityCollection = roomDOA.getCollection();
        roomTypeEntityCollection = roomTypeDOA.getRoomTypeCollection();
        
        Vector row;
        for(RoomEntity entity : roomEntityCollection) {
            if(entity.getRoomTypeID() == roomTypeIDdetail) {
                row = new Vector();
                row.add(entity.getRoomID());
                row.add(entity.getRoomName());
                row.add(entity.getRoomStatus());
                row.add(roomTypeRateDetails);
                row.add(roomTypeNameDetails);
                dataDetails.add(row);
            }
        }
        roomTypeDetailsModel.setDataVector(dataDetails, headerDetails);
        tblRoomTypeDetail.setModel(roomTypeListModel);
    }
    private void setHeaderDetail() {
        headerDetails = new Vector();
        dataDetails = new Vector();
        headerDetails.add("Room ID");
        headerDetails.add("Room Name");
        headerDetails.add("Room Status");
        headerDetails.add("Room Rate");
        headerDetails.add("Room TypeName");
        roomTypeDetailsModel.setDataVector(dataDetails, headerDetails);
        tblRoomTypeDetail.setModel(roomTypeDetailsModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jtable = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRoomTypeList = new javax.swing.JTable();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRoomTypeDetail = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        jLabel7.setText("Rate");

        jLabel6.setText("Room Type Name");

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0);
        flowLayout2.setAlignOnBaseline(true);
        jPanel3.setLayout(flowLayout2);

        jLabel2.setBackground(new java.awt.Color(0, 0, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Room Type");
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(jLabel2);

        jButton1.setText("Search");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setMargin(new java.awt.Insets(2, 0, 2, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField2))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(16, 16, 16)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(368, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setForeground(new java.awt.Color(102, 0, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(102, 51, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(51, 0, 255));

        tblRoomTypeList.setForeground(new java.awt.Color(102, 51, 255));
        tblRoomTypeList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRoomTypeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRoomTypeListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRoomTypeList);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setForeground(new java.awt.Color(102, 51, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(51, 0, 255));

        tblRoomTypeDetail.setForeground(new java.awt.Color(102, 51, 255));
        tblRoomTypeDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblRoomTypeDetail);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Details", jPanel6);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jButton3.setText("Details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton3))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnInsert)
                        .addGap(23, 23, 23)
                        .addComponent(jButton2)
                        .addGap(23, 23, 23)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addGap(26, 26, 26)
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        jtable.addTab("Room Type List", jPanel5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtable)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtable)
        );

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        RoomTypeDialogInsert roomTypeDialog = new RoomTypeDialogInsert(JFrame, true);
        roomTypeDialog.setVisible(true);
        showData();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        int rowToUpdate = tblRoomTypeList.getSelectedRow();
        if(rowToUpdate == -1) {
            JOptionPane.showMessageDialog(this, "Must chose a row to update");
            return;
        }
        roomTypeEntity = roomTypeEntityCollection.get(rowToUpdate);
        RoomTypeDialogUpdate roomTypeDialog = new RoomTypeDialogUpdate(JFrame, true, roomTypeEntity);
        roomTypeDialog.setVisible(true);
        showData();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int rowToDelete = tblRoomTypeList.getSelectedRow();
        if(rowToDelete == -1) {
            JOptionPane.showMessageDialog(this, "Must chose a row to update");
            return;
        }
        int roomTypeIDToDelete = (int)tblRoomTypeList.getValueAt(rowToDelete, 0);
        if(!isRoomTypeIDCanDelete(roomTypeIDToDelete)) {
            roomTypeDOA = new RoomTypeDAO();
            roomTypeDOA.delete(roomTypeIDToDelete);
        } else {
            JOptionPane.showMessageDialog(this, "There a room have this roomtype");
        }
        showData();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private boolean isRoomTypeIDCanDelete(int roomTypeToDelete) {
        roomDOA = new RoomDAO();
        roomEntityCollection = roomDOA.getCollection();
        for(RoomEntity entity : roomEntityCollection ) {
            if(roomTypeToDelete == entity.getRoomTypeID()) {
                return true;
            }
        }
        return false;
    }
    
    private void tblRoomTypeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRoomTypeListMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblRoomTypeListMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int index = tblRoomTypeList.getSelectedRow();
        if(index == -1) {
            JOptionPane.showMessageDialog(this, "Chosse a row");
            return;
        }
        int roomTypeIDDetails = (int)tblRoomTypeList.getValueAt(index, 0);
        double roomRateDetails = (double)tblRoomTypeList.getValueAt(index, 2);
        String roomTypeNameDetails = (String)tblRoomTypeList.getValueAt(index, 1);
        setDetailsModel(roomTypeIDDetails, roomRateDetails, roomTypeNameDetails);
        System.out.println("Index: "+index + "\tID: "+roomTypeIDDetails);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTabbedPane jtable;
    private javax.swing.JTable tblRoomTypeDetail;
    private javax.swing.JTable tblRoomTypeList;
    // End of variables declaration//GEN-END:variables

    @Override
    public void formDisplayCentral() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public boolean checkEmptyField() {
        return false;
    }

    @Override
    public void showData() {
        setHeaderList();
        roomTypeListModel.setRowCount(0);
        roomTypeDOA = new RoomTypeDAO();
        roomTypeEntityCollection = new Vector<>(roomTypeDOA.getRoomTypeCollection());
        for(RoomTypeEntity entity : roomTypeEntityCollection) {
            row = new Vector();
            row.addElement(entity.getRoomTypeID());
            row.addElement(entity.getRoomTypeName());
            row.addElement(entity.getRoomTypeRate());
            row.addElement(entity.getRoomTypeNote());
            data.add(row);
        }
    }
}
